name: cineverse
description: Cinema AI Tracker App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  dio: ^5.4.0
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.2
  path: ^1.9.0
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  google_generative_ai: ^0.4.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  intl: ^0.19.0
  url_launcher: ^6.2.5
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.2.2
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.9.0
  google_sign_in: ^7.2.0
  flutter_litert_lm: ^0.3.0
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2
  device_info_plus: ^11.1.0
  table_calendar: ^3.1.2
  qr_flutter: ^4.1.0
  speech_to_text: 7.2.0
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations.json
