import 'dart:convert';
import 'dart:typed_data';
import 'package:google_generative_ai/google_generative_ai.dart';
import '../core/constants.dart';
import '../models/media_item.dart';
import '../models/chat_message.dart';
import 'ai_models.dart';

class AiService {
 GenerativeModel get model=>GenerativeModel(model:AppConstants.geminiModel,apiKey:AppConstants.geminiApiKey);
 void check(){if(AppConstants.geminiApiKey.trim().isEmpty)throw StateError('GEMINI_API_KEY is not configured');}
 Future<String> text(String prompt) async{check();final r=await model.generateContent([Content.text(prompt)]);return r.text?.trim()??'لم يتم الحصول على إجابة.';}
 Future<String> chat(String q,List<ChatMessage> history)=>text('You are CineVerse AI. Answer in the same language as the user. User question: $q');
 Future<AiSummary> summarize(MediaItem i) async{final raw=await text('Return JSON only with summary,strengths,audience,mood,similarTo. Analyze '+i.title+': '+i.overview);try{final j=jsonDecode(raw);return AiSummary(summary:'${j['summary']??''}',strengths:List<String>.from(j['strengths']??[]),audience:'${j['audience']??''}',mood:'${j['mood']??''}',similarTo:List<String>.from(j['similarTo']??[]));}catch(_){return AiSummary(summary:raw,strengths:const [],audience:'',mood:'',similarTo:const []);}}
 Future<WorthWatching> worthWatching(MediaItem i) async{final raw=await text('Return JSON only with verdict,score,reason,forWhom,againstWhom,watchIf,skipIf. Analyze '+i.title+': '+i.overview);try{final j=jsonDecode(raw);return WorthWatching(verdict:'${j['verdict']??''}',score:(j['score'] as num?)?.toDouble()??0,reason:'${j['reason']??''}',forWhom:'${j['forWhom']??''}',againstWhom:'${j['againstWhom']??''}',watchIf:'${j['watchIf']??''}',skipIf:'${j['skipIf']??''}');}catch(_){return WorthWatching.empty();}}
 Future<String> explainEnding(MediaItem i)=>text('Explain the ending of '+i.title+'. Clearly label spoilers. '+i.overview);
 Future<MoodResult> classifyMood(String q) async{final raw=await text('Return JSON only with detectedMood,confidence,explanation,genres,avoidGenres,movies,anime. Mood: '+q);try{final j=jsonDecode(raw);return MoodResult(detectedMood:'${j['detectedMood']??''}',confidence:(j['confidence'] as num?)?.toDouble()??0,explanation:'${j['explanation']??''}',genres:List<String>.from(j['genres']??[]),avoidGenres:List<String>.from(j['avoidGenres']??[]),movies:List<String>.from(j['movies']??[]),anime:List<String>.from(j['anime']??[]));}catch(_){return MoodResult.empty();}}
 Future<PosterAnalysis> analyzePoster(Uint8List bytes) async{check();final m=GenerativeModel(model:AppConstants.geminiVisionModel,apiKey:AppConstants.geminiApiKey);final r=await m.generateContent([Content.multi([DataPart('image/jpeg',bytes),TextPart('Return JSON only with type,genres,audience,mood,colors,colorMeaning,symbols,verdict. Analyze this poster.')])]);final raw=r.text??'';try{final j=jsonDecode(raw);return PosterAnalysis(type:'${j['type']??''}',genres:List<String>.from(j['genres']??[]),audience:'${j['audience']??''}',mood:'${j['mood']??''}',colors:List<String>.from(j['colors']??[]),colorMeaning:'${j['colorMeaning']??''}',symbols:List<String>.from(j['symbols']??[]),verdict:'${j['verdict']??''}');}catch(_){return PosterAnalysis.empty();}}
 Future<TasteAnalysis> analyzeTaste(List<MediaItem> items) async{final data=items.take(30).map((x)=>x.title+'|'+x.genres.join(',')+'|'+(x.userRating?.toString()??'')).join('\n');final raw=await text('Return JSON only with archetype,personality,patterns,strengths,blindSpots,topGenres,avoidedGenres,recommendation. Library:\n'+data);try{final j=jsonDecode(raw);return TasteAnalysis(archetype:'${j['archetype']??''}',personality:'${j['personality']??''}',patterns:List<String>.from(j['patterns']??[]),strengths:'${j['strengths']??''}',blindSpots:'${j['blindSpots']??''}',topGenres:List<String>.from(j['topGenres']??[]),avoidedGenres:List<String>.from(j['avoidedGenres']??[]),recommendation:'${j['recommendation']??''}');}catch(_){return TasteAnalysis.empty();}}
}